<?php

namespace app\member\controller;

use app\member\model\BaseModel;
use app\validate\SearchValidate;
use cmf\controller\HomeBaseController;
use think\facade\Validate;
use app\validate\MemberValidate;
use think\Db;


class FansController extends HomeBaseController
{

    //优先执行判断登录状态

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->token = $this->request->patch('token');

        //判断token的传值
        if (isset($_SERVER["HTTP_TOKEN"])){
            $this->user = $this->check_user_login($_SERVER["HTTP_TOKEN"]);//验证用户
        }else{
            $this->user = $this->check_user_login($this->token); //验证用户
        }
        if (!$this->user){
            $this->ajaxResult(-1,'请登录后再试!');
        }

    }


    /**
     * 我的粉丝
     *token 用户token
     */
    public function lenderMe()
    {

        $data = $this->request->param();

        $re = Db::table('cmf_fans')
            ->alias('f')
            ->join('cmf_member m','f.user_id = m.id','LEFT')
            ->field('m.user_nickname,m.avatar,m.id')
            ->where('follow_id',$this->user['user_id'])
            ->select();

        $this->ajaxResult(1,'请求成功',$re);

    }


    /**
     * 我的粉丝个人资料
     *token 用户token
     */

    public function lenderMe_personal()
    {
        $id = $this->request->param('id');
        $errorInfo = (new SearchValidate())->goCheck('lsg_personal');
        if ($errorInfo !== true) $this->ajaxResult(-1, $errorInfo['msg'], $errorInfo['data']);

        $info = Db::table('cmf_member')
            ->alias('m')
            ->join('cmf_user_profession p','p.user_id = m.id','LEFT')
            ->where(['m.id' => $id])
            ->field([
                    'm.id',//用户id
                    'm.user_nickname', //昵称
                    'm.avatar', //头像
                    'm.label_name', //标签名
                    'p.id as profession_id', //工种id
                    'p.profession_price', //工种价格
                    'p.profession_name', //工种价格
                    'm.disabled_time', //不接单时间
                    'm.content', //个人说明
                    'm.show_picture', //展示图片
                ]
            )->find();
        $status  = Db::table('cmf_fans')->where('follow_id',$info['id'])->field('status')->find();

        $info['status'] = $status['status'];

//        $info['status'] = Db::table('cmf_fans')->where('follow_id',$info['id'])->field('status')->find()['status'];

        if(!empty($info['label_name'])){
            $info['label_name']=json_decode($info['label_name']);
        }else{
            $info['label_name'] = [];
        }
        if(!empty($info['disabled_time'])){
            $info['disabled_time']=json_decode($info['disabled_time']);
        }
        if(!empty($info['show_picture'])){
            $info['show_picture']=json_decode($info['show_picture']);
        }else{
            $info['show_picture'] = [];
        }
        $info['profession_price'] = Db::table('cmf_user_profession')
            ->where( 'profession_price> 0 ' )
            ->min('profession_price');

        $this->ajaxResult(1,'成功',$info);
    }


    /**
     * 我的关注
     *token 用户token
     */

    public function followMe()
    {

        $data = $this->request->param();

        $re = Db::table('cmf_fans')
            ->alias('f')
            ->join('cmf_member m','f.follow_id = m.id','LEFT')
            ->field('m.user_nickname,m.avatar,m.id')
            ->where('user_id',$this->user['user_id'])
            ->select();

        $this->ajaxResult(1,'请求成功',$re);

    }


    /**
     * 我的粉丝个人资料
     *token 用户token
     */

    public function followMe_personal()
    {
        $id = $this->request->param('id');
        $errorInfo = (new SearchValidate())->goCheck('lsg_personal');
        if ($errorInfo !== true) $this->ajaxResult(-1, $errorInfo['msg'], $errorInfo['data']);

        $info = Db::table('cmf_member')
            ->alias('m')
            ->join('cmf_user_profession p','p.user_id = m.id','LEFT')
            ->where(['m.id' => $id])
            ->field([
                    'm.id',//用户id
                    'm.user_nickname', //昵称
                    'm.avatar', //头像
                    'm.label_name', //标签名
                    'p.id as profession_id', //工种id
                    'p.profession_price', //工种价格
                    'p.profession_name', //工种价格
                    'm.disabled_time', //不接单时间
                    'm.content', //个人说明
                    'm.show_picture', //展示图片
                ]
            )->find();
        $status  = Db::table('cmf_fans')->where('follow_id',$info['id'])->field('status')->find();

        $info['status'] = $status['status'];

//        $info['status'] = Db::table('cmf_fans')->where('follow_id',$info['id'])->field('status')->find()['status'];

        if(!empty($info['label_name'])){
            $info['label_name']=json_decode($info['label_name']);
        }else{
            $info['label_name'] = [];
        }
        if(!empty($info['disabled_time'])){
            $info['disabled_time']=json_decode($info['disabled_time']);
        }
        if(!empty($info['show_picture'])){
            $info['show_picture']=json_decode($info['show_picture']);
        }else{
            $info['show_picture'] = [];
        }
        $info['profession_price'] = Db::table('cmf_user_profession')
            ->where( 'profession_price> 0 ' )
            ->min('profession_price');

        $this->ajaxResult(1,'成功',$info);
    }





    /**
     * 关注
     */

    public function follow(){


        $data = $this->request->param();


        $insert = [
          'user_id' => $this->user['user_id'],
          'follow_id' => $data['id'],
          'status' => 1,
          'create_time' =>time(),
        ];

        $re = Db::table('cmf_fans')->insert($insert);

        if ($re >0 ){
            $this->ajaxResult(1,'关注成功');
        } else{
            $this->ajaxResult(1,'没有数据');
        }

    }


    /**
     * 取消关注
     */

    public function DelFollow(){


        $data = $this->request->param();


        $where = [
            'user_id' => $this->user['user_id'],
            'follow_id' => $data['id'],
        ];

        $re = Db::table('cmf_fans')->where($where)->delete();

        if ($re >0 ){
            $this->ajaxResult(1,'取消关注成功');
        } else{
            $this->ajaxResult(1,'没有数据');
        }

    }





}